title: Just the Docs Excersize
description: Description of Just The Docs pages
theme: just-the-docs

url: https://Nataziet.github.io/JustTheDocs

aux_links:
  Template Repository: https://github.com/just-the-docs/Nataziet/JustTheDocs
color_scheme: dark
